### ISSUE TITLE
"Unfollowed you" notification instead of "blocked from you"

### ISSUE THREAD

**Issue by AnnoyedUnicorn** [PLhery/unfollowNinja#27] opened 2020-08-05 17:31 UTC
UnfollowNinja sends a notification that @userSoftBlocked unfollowed you if you block @userSoftBlocked for a moment and then unblock them.

## Expected Behavior
A notification that the user (I) blocked @userSoftBlocked.

## Current Behavior
A notification that @userSoftBlocked  unfollowed the user.

## Steps to Reproduce
1. Find a user that follows you ;
2. Block them for a second ant then unblock them ;
3. Wait for the DM from your unfollowNinja instance.

**Comment by plhery** [comment] 2020-08-07 14:37
Hello, thank you for the report :)

It would be hard to fix with the current way the project works:
- The list of followers are checked every 5 minutes
- If someone disappears, it checks the status of the user (are they blocked, are they still on twitter etc...)
At that time, the user is not blocked anymore it's too late to know via the APIs it has been soft-blocked

If you have any idea of how to do it I'll take it, maybe with the future streaming APIs that will be released soon, but that would probably be overkill just for this purpose..

**Closed as completed** 2020-08-16 14:00 UTC

**Comment by ghost** [comment] 2022-04-30 09:56
Maybe this could be done by also tracking the following list in addition to followers, or would that be too much burden on the server / rate limits?

**Comment by plhery** [comment] 2022-05-01 18:16
Hello,

The problem is that both could unfollow each other at the same time without any softblock - and also I can't know which one of the two softblocked the other

At the end of the day, if you softblocked one of your followers, you don't need unfollowninja to remind you that you did this.

**Comment by ghost** [comment] 2022-05-01 18:19
> At the end of the day, if you softblocked one of your followers, you don't need unfollowninja to remind you that you did this.

No, you don't. But if *they* softblocked you, then sometimes you may be left wondering "wait, did they softblock me or did I never follow them back in the first place?" So IMO a simple "softblocked" or "unfollowed each other" message without specifying whether you or the other person did it would still be more useful than the status quo.

**Comment by plhery** [comment] 2022-05-01 18:27
OK I keep that idea in mind for the future.

The main issue here is technical, it could be hard to know if "two persons unfollow each other at the same time", given that on unfollow-monkey.com with free accounts, we check the state of the followers every 45min.

If someone unfollows you and you unfollow them back 30min later, this would be wrongfully detected as a "softblock".

Plus checking the state of the followings would indeed require more ressources, but could be worthwhile for other future features.
